a Bash script that transfers a file from our client to a server:

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,21 +1,25 @@
 #!/usr/bin/env bash
-
-# Function to display usage
-usage() {
-  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-}
-
 # Check if number of arguments is less than 4, display usage and exit
-if [ "$#" -lt 4 ]; then
+
+if [ $# -lt 4 ]
+then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
 fi
 
 # Assigning parameters to variables
-PATH_TO_FILE="$1"
-IP="$2"
-USERNAME="$3"
-PATH_TO_SSH_KEY="$4"
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
 
 # Transfer the file using scp to the user's home directory (~)
-scp -o "StrictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@IP:~/"
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# check success
+if [ $? -eq 0 ]
+then
+	echo "File transfer success"
+else
+	echo "Fail"
+fi
